### PR TITLE
added a hover tool to the station locations

### PR DESCRIPTION
**Pull request by maxballison**
Pretty self explanatory, adds a feature that allows hovering to get station names. The station dots are fairly small, though, so we can think about increasing their size?

### CODE REVIEW

**Comment by brendanjmeade** [comment]
@maxballison This sounds awesome.  I've merged the PR and pulled it down to my laptop.  I can see that there are two new items in the tool bar to the far-right of the figure (see image below).  Are there steps that I take to get the hover over to activate?  I've tried place the cursor over a station but haven't had luck in terms of seeing something pop up.  Guidance welcome!

Screenshot 2024-09-18 at 10 56 21 PM

**Comment by maxballison** [comment]
Hey Brendan,

Huh, it should be working. The two icons in the sidebar represent the two
hover tools—one for the first dataset and one for the second. It seems like
you have the right one selected. As I mentioned, the circles are super
small (and I was afraid to change their size without asking first), so you
seemingly have to hover over the *exact *pixel to get it to show the name.
Below is a screenshot showing what mine looks like. If you can't get this
behavior, maybe see if it works if you increase the circle radii? Just let
me know and I can try to figure it out too!

Best,
Max
[image: Screenshot 2024-09-18 at 11.03.53 PM.png]

**Comment by brendanjmeade** [comment]
Got it and it's working for me.  This is very nice!  Cool and immediately useful.  Getting the cursor exactly over the points is hard.  You mentioned larger circles.  Would they provide a larger number of pixels to hover over or would you have to hover over exactly the center?  Give it a try.

**Comment by maxballison** [comment]
It *does *seem like increasing the size of the points is a pretty effective
solution. Upon further testing, though, I've found that the names somehow
disappear whenever the velocity slider is moved. Very strange and
unexpected behavior. I'll try to tackle this tomorrow to make sure that the
dots are easy to hover over, and no other features mess with the names.

**Pull request merged**
